[package]
name = "routing_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
yew-router = "*"
gloo = "*"
connect4-lib = "*"
#wasm_bindgen = "*"
#yew_functional = "*"