[package]
name = "ece421_group_project_3_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.25.0"
rust-argon2 = "1.0.0"
rocket = "0.4.10"